export const festivalPrompts = [
    "Colorful tents at an outdoor music festival.",
    "Crowds dancing at a lively cultural festival.",
    "Glowing lanterns at a nighttime festival.",
    "Vibrant parade with performers in costumes.",
    "Street fair with food stalls and bustling activity.",
    "Stage with musicians performing at a music festival.",
    "Fireworks illuminating the sky at a celebration.",
    "Traditional dances at a cultural festival.",
    "Art installations at an arts and crafts festival.",
    "Street performers entertaining crowds.",
    "Decorated floats in a festive parade.",
    "A carnival with rides and attractions.",
    "Colorful banners and flags at a festival.",
    "Community gathering with diverse activities.",
    "Artistic displays at a cultural heritage festival.",
    "Ethnic food stalls at a multicultural festival.",
    "Folk music performances at a traditional festival.",
    "Joyful attendees participating in games.",
    "Decorated streets during a local celebration.",
    "Traditional ceremonies and rituals at a festival."
];

export const vintageClassicPrompts = [
    "Antique furniture in a vintage interior.",
    "Retro decor in a classic living space.",
    "Aged books on shelves in an old library.",
    "Vintage car parked on a historic street.",
    "Classic gramophone in a nostalgic room.",
    "Vintage shopfront on a quaint street.",
    "Rustic interior with aged wooden furnishings.",
    "Old-fashioned diner with vinyl booths.",
    "Victorian-era room with ornate details.",
    "Vintage typewriter on an antique desk.",
    "Retro record player in a nostalgic environment.",
    "Classic tea set on a vintage table.",
    "Antique clock on a mantle in a historic house.",
    "Old-fashioned storefront with vintage signage.",
    "Vintage telephone on a classic desk.",
    "Retro-style cafe with checkerboard floors.",
    "Vintage sewing machine in a classic room.",
    "Classic movie theater with retro decor.",
    "Nostalgic radio in a vintage setting.",
    "Antique market with timeless collectibles."
];

export const streetCityPrompts = [
    "Busy city streets bustling with pedestrians.",
    "High-rise buildings lining an urban street.",
    "Cityscape with traffic bustling through streets.",
    "A cobblestone street in a historic district.",
    "Skyscrapers towering over a city avenue.",
    "A colorful alleyway in the heart of the city.",
    "Streetlights illuminating a nighttime city scene.",
    "A vibrant market street full of vendors.",
    "A modern city boulevard with sleek architecture.",
    "Pedestrian street with cafes and shops.",
    "A downtown street with historic architecture.",
    "City streets alive with urban art and graffiti.",
    "A bustling financial district thoroughfare.",
    "A lively street corner with street performers.",
    "A busy intersection in a metropolitan area.",
    "A tree-lined avenue in the heart of the city.",
    "A city street with historic landmarks.",
    "A narrow street in a charming old town.",
    "A modern cityscape with skyscrapers and lights.",
    "A cosmopolitan street with diverse storefronts."
];

export const solidColorPrompts = [
    "Clean and crisp solid white backdrop.",
    "Bold and sophisticated solid black background.",
    "Neutral and versatile solid gray backdrop.",
    "Soft and inviting solid beige background.",
    "Timeless and professional solid navy blue backdrop.",
    "Elegant and striking solid red background.",
    "Fresh and lively solid green backdrop.",
    "Modern and chic solid purple background.",
    "Subtle and charming solid pink backdrop.",
    "Warm and adaptable solid brown background.",
    "Refined and luxurious solid burgundy backdrop.",
    "Bright and cheerful solid yellow background.",
    "Rich and opulent solid gold backdrop.",
    "Vibrant and energetic solid orange background.",
    "Tranquil and calming solid sky blue backdrop.",
    "Sleek and stylish solid silver background.",
    "Sharp and sophisticated solid charcoal backdrop.",
    "Fresh and serene solid pastel green background.",
    "Dynamic and bold solid electric blue backdrop.",
    "Classic and earthy solid taupe background."
];

export const beachPrompts = [
    "Palm trees swaying on a sun-kissed beach.",
    "Gentle waves lapping onto a serene shoreline.",
    "Silhouetted palm trees against a vivid sunset.",
    "Crystal-clear waters in a tropical beach scene.",
    "A hammock nestled between palm trees on the beach.",
    "A sun-soaked beach with pristine white sand.",
    "Colorful surfboards lining a picturesque beach.",
    "A beach umbrella casting shade on golden sands.",
    "Seashells scattered along a peaceful beach.",
    "A bustling beachside cafe with ocean views.",
    "A palm-fringed beach under a cloudless sky.",
    "Sailboats dotting the horizon from the beach.",
    "Rock formations meeting crashing waves on the shore.",
    "A sunset casting hues of orange on the beach.",
    "Lush tropical foliage framing a tranquil beach.",
    "Footprints tracing the edge of the calm shoreline.",
    "A lone lighthouse overlooking a serene beach.",
    "Vibrant beach towels adorning the sandy coast.",
    "Beachgoers enjoying a game of volleyball.",
    "Seagulls soaring above a peaceful stretch of beach."
];

export const holidayPrompts = [
    "concrete surface, white and grey modern elegant minimalistic christmas decorations, editorial photo, behance, above shot, flatlay",
    "fresh snow surface, white fluffy texture, silver christmas decor, festive, editorial photo, behance, flatlay, above shot",
    "crumpled silk surrounded by elegant christmas decorations, festive, minimalistic, ascetic elegance, flatlay, above shot",
    "empty surface, surrounded by sparse ascetic christmas festive decor, editorial photo, behance",
    "concrete surface, white and grey modern elegant minimalistic christmas decorations, editorial photo, behance, flatlay, above shot",
    "fresh snow surface, white fluffy texture, silver christmas decor, festive, editorial photo, behance, above shot, flatlay",
    "marble cylindrical platform in front of christmas tree with a twinkle night decor ornaments lights, festive, elegant, gold, editorial photo, bokeh shot",
    "empty metallic pedestal, surrounded by christmas decorations, elegant festive, editorial photo, bokeh shot",
    "white marble slab cylindrical platform in front of christmas tree with a twinkle night decor ornaments lights, festive, elegant, gold, editorial photo, bokeh shot",
    "wooden tabletop with a christmas tree in the background, festive decor, editorial photo, bokeh shot"    
]

export const flatLaysPrompts = [
    "detailed photo of an object on wavy silk, soft light and shadows, high quality, realistic, flatlay, above shot",
    "linen fabric surface, soft warm morning light, above shot, editorial photo, behance, above shot, flatlay",
    "sandy beach surface, above shot, editorial photo, behance, flatlay",
    "shiny red silk surface, above shot, editorial photo, behance, flatlay",
    "leaves and branches on sand, above shot, behance, professional product photography, flatlay",
    "flatlay photo, leaves and branches on velvet, behance, professional product photography, above shot",
    "beach spa scene, editorial photo, flatlay composition, behance, professional product photography, above shot",
    "clay spa scene, editorial photo, flatlay composition, behance, professional product photography, above shot",
    "beach spa scene, editorial photo, flatlay composition, behance, professional product photography, above shot",
    "velvet pillow over metallic stones, behance, above shot, flatlay",
    "limestone slab over beach pebbles, behance, flatlay, above shot",
    "velvet pillow over stones, behance, editorial photo, flatlay, above shot",
    "metallic platter over rough stones, behance, flatlay, above shot",
    "pearl iridescent slab over bright pebbles, behance, flatlay, above shot",
    "linen fabric surface, soft warm morning light, above shot, flatlay, editorial photo, behance",
    "wavy silk, ambient soft light, editorial photo, above shot, flatlay, behance",
    "silk drapes, ethereal, pastel, morning light, above shot, flatlay, editorial photo, behance",
    "rough grey stones, granite pebble texture, low key, editorial photo, flatlay, above shot",
    "sandstone pebbles on sand, matt rough stone surface, warm soft light, above shot, flatlay",
    "rough grey stones, granite pebble texture, low key, editorial photo, above shot, flatlay",
    "top view of beach sand at sunset, editorial photo, behance, above shot, flatlay",
    "tulip on metallic silk, editorial photo, behance, above shot, flatlay, professional product photography",
    "top view of beach sand, tropical flower, editorial photo, behance, above shot, flatlay",
    "sandstone podium on rough sand, above shot, flatlay, behance, editorial photo",
    "minimalistic limestone circular platform, cloudy overcast daylight, above shot, flatlay, editorial photo"
]

export const minimalisticPrompts = [
    "white marble countertop and wall, editorial photo, behance, bokeh shot, closeup",
    "stone tabletop, stucco wall, editorial photo, behance, bokeh shot, closeup",
    "marble countertop, concrete wall, monochromatic, editorial photo, behance, bokeh shot, closeup",
    "concrete countertop, smooth wall, editorial photo, behance, bokeh shot, closeup",
    "modern marble interior minimalistic countertop, professional product photography, behance, editorial photo, bokeh shot",
    "rough concrete countertop, textured surfaces, behance, editorial photo, bokeh shot",
    "sandstone countertop, sandstone wall, professional product photography, behance, editorial photo, bokeh shot",
    "rough white limestone, seaside blue sky bokeh background, professional product photography, behance, editorial photo, bokeh shot",
    "matt metallic iridescent anodized pedestal, ethereal cloudy sky background, early morning light, editorial photo, behance, bokeh shot",
    "marble pedestal, scenic cloudy sky above sea background, warm evening light, editorial photo, behance, bokeh shot",
    "rough limestone pedestal, warm summer light, azure sea and beach in distant background, editorial photo, behance, bokeh shot",
    "white marble platforms, editorial photo, behance, bokeh shot, closeup",
    "stone tabletop, stucco wall, editorial photo, behance, bokeh shot, closeup",
    "marble pedestal, scenic cloudy sky above sea background, warm evening light, editorial photo, behance, bokeh shot",
    "marble and silk drapes, ethereal, pastel, morning light, editorial photo, behance, professional photography",
    "modern marble interior minimalistic countertop, professional product photography, behance, editorial photo, bokeh shot",
    "marble pedestal, scenic cloudy sky above sea background, warm evening light, editorial photo, behance, bokeh shot",
    "modern marble interior minimalistic countertop, professional product photography, behance, editorial photo, bokeh shot",
    "rough concrete countertop, textured surfaces, behance, editorial photo, bokeh shot",
    "sandstone countertop, sandstone wall, professional product photography, behance, editorial photo, bokeh shot",
    "marble countertop, silk curtains, monochromatic, editorial photo, behance, professional photography, bokeh shot",
    "rough concrete countertop, velvet curtains, monochromatic, editorial photo, behance, professional photography, bokeh shot",
]

export const naturePrompts = [
    "rough green stone in a lush foggy jungle, surrounded by blooming tiny flowers, professional product photography, behance, editorial photo",
    "rough black stone on a meadow with a teal evening forest in the background, professional product photography, behance, editorial photo, bokeh shot",
    "rough limestone in a foggy morning orchard, surrounded by blooming trees, sunlit, professional product photography, behance, bokeh shot, editorial photo",
    "white limestone rocks and on beach, warm summer light, azure sky and sea background, editorial photo, behance, bokeh shot",
    "white limestone rocks and tiny flowers, beach vibes, warm summer light, editorial photo, behance, bokeh shot",
    "stones and plants, warm evening light, editorial photo, behance, bokeh shot",
    "marble pedestal surrounded by rough rocks, cool blue hour evening light, editorial photo, behance, boke",
    "marble countertop, ascetic interior, tree branch, blue hour evening light, ethereal, iridescent, editorial photo, behance, bokeh shot",
    "marble pedestal, flowery branch, warm morning light, ethereal, iridescent, editorial photo, behance, bokeh shot",
    "marble countertop, ascetic interior, tree branch, warm evening light, ethereal, iridescent, editorial photo, behance, bokeh shot",
    "granite rocks in a sunny woods, warm morning light, editorial photo, behance, bokeh shot",
]

export const fabricBackgroundPrompts =  [
    "crumpled linen, warm tones, sunlight aesthetic, editorial photo, behance, professional photography",
    "silk drapes, ethereal, pastel, morning light, editorial photo, behance, professional photography",
    "beach sand at sunset, editorial photo, behance, bokeh shot",
    "limestone podium, background of linen waves, mediterranean, editorial photo, behance, professional photography, bokeh shot",
    "waves of silk, ethereal, pastel, soft light, editorial photo, behance, bokeh shot",
    "linen fabric surface, soft warm morning light, above shot, editorial photo, behance, bokeh shot",
    "waves of linen, ethereal, pastel, blue hour, cool light, editorial photo, behance, bokeh shot",
    "waves of velvet, ethereal, pastel, morning light, editorial photo, behance, bokeh shot",
    "waves of silk, ethereal, pastel, soft light, editorial photo, behance, bokeh shot",
]