export const festivalPrompts = [
    "Colorful tents at an outdoor music festival.",
    "Crowds dancing at a lively cultural festival.",
    "Glowing lanterns at a nighttime festival.",
    "Vibrant parade with performers in costumes.",
    "Street fair with food stalls and bustling activity.",
    "Stage with musicians performing at a music festival.",
    "Fireworks illuminating the sky at a celebration.",
    "Traditional dances at a cultural festival.",
    "Art installations at an arts and crafts festival.",
    "Street performers entertaining crowds.",
    "Decorated floats in a festive parade.",
    "A carnival with rides and attractions.",
    "Colorful banners and flags at a festival.",
    "Community gathering with diverse activities.",
    "Artistic displays at a cultural heritage festival.",
    "Ethnic food stalls at a multicultural festival.",
    "Folk music performances at a traditional festival.",
    "Joyful attendees participating in games.",
    "Decorated streets during a local celebration.",
    "Traditional ceremonies and rituals at a festival."
];

export const vintageClassicPrompts = [
    "Antique furniture in a vintage interior.",
    "Retro decor in a classic living space.",
    "Aged books on shelves in an old library.",
    "Vintage car parked on a historic street.",
    "Classic gramophone in a nostalgic room.",
    "Vintage shopfront on a quaint street.",
    "Rustic interior with aged wooden furnishings.",
    "Old-fashioned diner with vinyl booths.",
    "Victorian-era room with ornate details.",
    "Vintage typewriter on an antique desk.",
    "Retro record player in a nostalgic environment.",
    "Classic tea set on a vintage table.",
    "Antique clock on a mantle in a historic house.",
    "Old-fashioned storefront with vintage signage.",
    "Vintage telephone on a classic desk.",
    "Retro-style cafe with checkerboard floors.",
    "Vintage sewing machine in a classic room.",
    "Classic movie theater with retro decor.",
    "Nostalgic radio in a vintage setting.",
    "Antique market with timeless collectibles."
];

export const streetCityPrompts = [
    "Busy city streets bustling with pedestrians.",
    "High-rise buildings lining an urban street.",
    "Cityscape with traffic bustling through streets.",
    "A cobblestone street in a historic district.",
    "Skyscrapers towering over a city avenue.",
    "A colorful alleyway in the heart of the city.",
    "Streetlights illuminating a nighttime city scene.",
    "A vibrant market street full of vendors.",
    "A modern city boulevard with sleek architecture.",
    "Pedestrian street with cafes and shops.",
    "A downtown street with historic architecture.",
    "City streets alive with urban art and graffiti.",
    "A bustling financial district thoroughfare.",
    "A lively street corner with street performers.",
    "A busy intersection in a metropolitan area.",
    "A tree-lined avenue in the heart of the city.",
    "A city street with historic landmarks.",
    "A narrow street in a charming old town.",
    "A modern cityscape with skyscrapers and lights.",
    "A cosmopolitan street with diverse storefronts."
];

export const solidColorPrompts = [
    "Clean and crisp solid white backdrop.",
    "Bold and sophisticated solid black background.",
    "Neutral and versatile solid gray backdrop.",
    "Soft and inviting solid beige background.",
    "Timeless and professional solid navy blue backdrop.",
    "Elegant and striking solid red background.",
    "Fresh and lively solid green backdrop.",
    "Modern and chic solid purple background.",
    "Subtle and charming solid pink backdrop.",
    "Warm and adaptable solid brown background.",
    "Refined and luxurious solid burgundy backdrop.",
    "Bright and cheerful solid yellow background.",
    "Rich and opulent solid gold backdrop.",
    "Vibrant and energetic solid orange background.",
    "Tranquil and calming solid sky blue backdrop.",
    "Sleek and stylish solid silver background.",
    "Sharp and sophisticated solid charcoal backdrop.",
    "Fresh and serene solid pastel green background.",
    "Dynamic and bold solid electric blue backdrop.",
    "Classic and earthy solid taupe background."
];

export const beachPrompts = [
    "Palm trees swaying on a sun-kissed beach.",
    "Gentle waves lapping onto a serene shoreline.",
    "Silhouetted palm trees against a vivid sunset.",
    "Crystal-clear waters in a tropical beach scene.",
    "A hammock nestled between palm trees on the beach.",
    "A sun-soaked beach with pristine white sand.",
    "Colorful surfboards lining a picturesque beach.",
    "A beach umbrella casting shade on golden sands.",
    "Seashells scattered along a peaceful beach.",
    "A bustling beachside cafe with ocean views.",
    "A palm-fringed beach under a cloudless sky.",
    "Sailboats dotting the horizon from the beach.",
    "Rock formations meeting crashing waves on the shore.",
    "A sunset casting hues of orange on the beach.",
    "Lush tropical foliage framing a tranquil beach.",
    "Footprints tracing the edge of the calm shoreline.",
    "A lone lighthouse overlooking a serene beach.",
    "Vibrant beach towels adorning the sandy coast.",
    "Beachgoers enjoying a game of volleyball.",
    "Seagulls soaring above a peaceful stretch of beach."
];
